# Generated by Django 5.2.4 on 2025-10-20 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
