# Generated by Django 5.2.4 on 2025-07-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_regimenfiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regimenfiscal',
            options={'ordering': ['codigo'], 'verbose_name': 'Régimen Fiscal', 'verbose_name_plural': 'Regímenes Fiscales'},
        ),
    ]
