# Generated by Django 5.2.4 on 2025-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='is_credito',
            field=models.BooleanField(default=False, verbose_name='Es Crédito'),
        ),
    ]
