# Generated by Django 5.2.4 on 2025-10-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_metodopago_is_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Condición de Pago',
                'verbose_name_plural': 'Condiciones de Pago',
            },
        ),
    ]
