# Generated by Django 5.2.4 on 2025-07-25 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('direccion', '0001_initial'),
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('origen', models.CharField(blank=True, choices=[('MEX', 'México'), ('USA', 'Estados Unidos'), ('OTR', 'Otro')], default='MEX', max_length=3, null=True, verbose_name='Origen')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('razon_social', models.CharField(blank=True, default=None, max_length=180, null=True, verbose_name='Razón Social')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('rfc', models.CharField(blank=True, max_length=15, null=True, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='Stock Mínimo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mayoreo')),
                ('precio_publico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Público')),
                ('clave_sat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave SAT (Producto o Servicio)')),
                ('iva', models.DecimalField(decimal_places=2, default=0.16, max_digits=5, verbose_name='IVA')),
                ('ieps', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IEPS')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_categoria', to='erp.categoria', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('unidad_sat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.unidadsat', verbose_name='Unidad SAT')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('proveedores', models.ManyToManyField(blank=True, to='erp.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_postal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_proveedor', to='erp.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
