# Generated by Django 5.2.4 on 2025-07-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_categoria_proveedor_producto_direccionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Monto de Crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_credito',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plazo de Crédito (días)'),
        ),
    ]
