# Generated by Django 5.2.4 on 2025-07-30 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_producto_stock_minimo_almacen_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['nombre'], 'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AddField(
            model_name='sucursal',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursal_almacen', to='erp.almacen', verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='precio_tipo',
            field=models.CharField(choices=[('MAY', 'Mayoreo'), ('PUB', 'Público')], default='PUB', max_length=4, verbose_name='Lista de precios'),
        ),
    ]
