# Generated by Django 5.2.4 on 2025-07-31 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_regimenfiscal_options'),
        ('erp', '0005_alter_almacen_options_alter_proveedor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ieps',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona',
            field=models.CharField(blank=True, choices=[('PERSONA FISICA', 'Persona Física'), ('PERSONA MORAL', 'Persona Moral')], default='PERSONA FISICA', max_length=20, null=True, verbose_name='Tipo de Persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado'),
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='latitud',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='longitud',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cuenta_clave',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Clave'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='otro_impuesto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Otro Impuesto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_clave',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Clave'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Nombres'),
        ),
    ]
