# Generated by Django 5.2.4 on 2025-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_remove_cliente_apellidos_remove_producto_ieps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion_fiscal',
            field=models.TextField(blank=True, help_text='Dirección fiscal de la empresa', null=True, verbose_name='Dirección Fiscal'),
        ),
    ]
