# Generated by Django 5.2.4 on 2025-08-07 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_regimenfiscal_options'),
        ('erp', '0007_empresa_direccion_fiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido_paterno', 'apellido_materno'), name='unique_nombre_completo'),
        ),
    ]
