# Generated by Django 5.2.4 on 2025-08-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_producto_nombre_cliente_unique_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clave_sat',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Clave SAT (Producto o Servicio)'),
        ),
    ]
