# Generated by Django 5.2.4 on 2025-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_producto_clave_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIJO', 'FIJO'), ('VIRT', 'VIRTUAL'), ('RUTA', 'RUTA')], default='FIJO', max_length=4, null=True, verbose_name='Tipo de almacen'),
        ),
    ]
