# Generated by Django 5.2.4 on 2025-08-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_almacen_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='erp.empresa', verbose_name='Empresa'),
        ),
    ]
