# Generated by Django 5.2.4 on 2025-08-19 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_almacen_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_empresa', to='erp.empresa', verbose_name='Empresa'),
        ),
    ]
