# Generated by Django 5.2.4 on 2025-08-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_sucursal_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('POTENCIAL', 'Potencial'), ('ESTANDAR', 'Estándar'), ('NO_CREDITO', 'No Crédito'), ('CREDITO_SEMANAL', 'Crédito Semanal'), ('EVENTUAL', 'Eventual'), ('BUEN_CLIENTE', 'Buen Cliente'), ('PREMIUM', 'Premium')], default='ESTANDAR', max_length=20, verbose_name='Tipo de Cliente'),
        ),
    ]
