# Generated by Django 5.2.4 on 2025-08-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='precio_tipo',
            field=models.CharField(choices=[('MAYOREO', 'Mayoreo'), ('PUBLICO', 'Público')], default='PUBLICO', max_length=15, verbose_name='Lista de precios'),
        ),
    ]
