# Generated by Django 5.2.4 on 2025-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_alter_cliente_precio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='total_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Total de Crédito'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('POTENCIAL', 'Potencial'), ('ESTANDAR', 'Estándar'), ('NO CREDITO', 'No Crédito'), ('CREDITO SEMANAL', 'Crédito Semanal'), ('EVENTUAL', 'Eventual'), ('BUEN CLIENTE', 'Buen Cliente'), ('PREMIUM', 'Premium')], default='ESTANDAR', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, choices=[('MEXICO', 'México'), ('USA', 'Estados Unidos'), ('OTRO', 'Otro')], default='MEXICO', max_length=10, null=True, verbose_name='Origen'),
        ),
    ]
