# Generated by Django 5.2.4 on 2025-08-22 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_proveedor_total_credito_alter_cliente_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='almacen',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='almacenes',
            field=models.ManyToManyField(blank=True, related_name='sucursales', to='erp.almacen', verbose_name='Almacenes'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, choices=[('MÉXICO', 'MÉXICO'), ('ESTADOS UNIDOS', 'ESTADOS UNIDOS'), ('OTRO', 'OTRO')], default='MÉXICO', max_length=20, null=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursal_encargado', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
