# Generated by Django 5.2.4 on 2025-08-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_remove_sucursal_almacen_sucursal_almacenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='horas_caducidad',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de horas para que un lote caduque después de su creación. 0 = No caduca', null=True, verbose_name='Horas de Caducidad'),
        ),
    ]
