# Generated by Django 5.2.4 on 2025-08-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_compra_compradetalle_pagoscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='erp.ordencompra', verbose_name='Orden de Compra'),
        ),
    ]
