# Generated by Django 5.2.4 on 2025-09-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_compra_orden_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_compra_encargado', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PROCESANDO', 'PROCESANDO'), ('FINALIZADA', 'FINALIZADA'), ('ALMACEN VIRTUAL', 'ALMACEN VIRTUAL'), ('ALMACEN', 'ALMACEN')], default='ALMACEN VIRTUAL', max_length=20, verbose_name='Estado'),
        ),
       migrations.RemoveField(
            model_name='compra',
            name='tiempo_recorrido',
        ),
        migrations.AddField(
            model_name='compra',
            name='tiempo_recorrido',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name="Tiempo Recorrido"),
        ),
    ]
