# Generated by Django 5.2.4 on 2025-09-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_ordencompra_encargado_alter_compra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscompra',
            name='fecha_pagar',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha a Pagar'),
        ),
    ]
