# Generated by Django 5.2.4 on 2025-09-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_pagoscompra_fecha_pagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Ruta')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='erp.almacen', verbose_name='Almacén')),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Chofer Asignado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta de Entrega',
                'verbose_name_plural': 'Rutas de Entrega',
                'ordering': ['nombre'],
            },
        ),
    ]
