# Generated by Django 5.2.4 on 2025-09-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_rutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='almacen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='erp.almacen', verbose_name='Almacén'),
        ),
    ]
