# Generated by Django 5.2.4 on 2025-09-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_metodopago_is_credito'),
        ('erp', '0025_alter_rutas_almacen'),
        ('inventario', '0010_loteinventario_inventario__ubicaci_55fa1e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Folio')),
                ('fase', models.CharField(choices=[('PRE VENTA', 'PRE VENTA'), ('EN CURSO', 'EN CURSO'), ('TERMINADA', 'TERMINADA'), ('CANCELADA', 'CANCELADA')], default='TERMINADA', max_length=20, verbose_name='Fase')),
                ('was_preventa', models.BooleanField(default=False, verbose_name='Fue Preventa')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='erp.almacen', verbose_name='Almacén afectado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='erp.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='erp.rutas', verbose_name='Ruta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='PagosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha_pagar', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha a Pagar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.metodopago', verbose_name='Método de Pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='erp.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='erp.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='erp.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalleLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Utilizada del Lote')),
                ('costo_unitario_lote', models.DecimalField(decimal_places=2, help_text='Costo del producto en este lote específico', max_digits=10, verbose_name='Costo Unitario del Lote')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('lote_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='inventario.loteinventario', verbose_name='Lote de Inventario')),
                ('venta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_utilizados', to='erp.ventadetalle', verbose_name='Detalle de Venta')),
            ],
            options={
                'verbose_name': 'Lote en Detalle de Venta',
                'verbose_name_plural': 'Lotes en Detalles de Venta',
                'constraints': [models.UniqueConstraint(fields=('venta_detalle', 'lote_inventario'), name='unique_venta_detalle_lote')],
            },
        ),
    ]
