# Generated by Django 5.2.4 on 2025-09-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_venta_pagosventa_ventadetalle_ventadetallelote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIJO', 'FIJO'), ('VIRT', 'VIRTUAL'), ('RUTA', 'RUTA'), ('COMP', 'COMPRA')], default='FIJO', max_length=4, null=True, verbose_name='Tipo de almacen'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PROCESANDO', 'PROCESANDO'), ('FINALIZADA', 'FINALIZADA')], default='ALMACEN VIRTUAL', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='IVA'),
        ),
    ]
