# Generated by Django 5.2.4 on 2025-09-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_almacen_tipo_alter_compra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ordencompradetalle',
            name='precio_unitario',
        ),
    ]
