# Generated by Django 5.2.4 on 2025-09-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_ordencompra_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Unidad')),
                ('tipo', models.CharField(blank=True, choices=[('CAMIÓN', 'CAMIÓN'), ('CAMIONETA', 'CAMIONETA'), ('TRÁILER', 'TRÁILER'), ('OTRO', 'OTRO')], default='CAMIÓN', max_length=20, null=True, verbose_name='Tipo de Vehículo')),
                ('placas', models.CharField(max_length=20, unique=True, verbose_name='Placas')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('capacidad_carga', models.DecimalField(decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=10, verbose_name='Capacidad de Carga (Tons)')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Vehicular',
                'verbose_name_plural': 'Unidades Vehiculares',
                'ordering': ['id'],
            },
        ),
    ]
