# Generated by Django 5.2.4 on 2025-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_unidadvehicular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadvehicular',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='unidadvehicular',
            name='capacidad_carga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=10, null=True, verbose_name='Capacidad de Carga (Tons)'),
        ),
        migrations.AlterField(
            model_name='unidadvehicular',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='unidadvehicular',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='unidadvehicular',
            name='placas',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Placas'),
        ),
    ]
