# Generated by Django 5.2.4 on 2025-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_unidadvehicular_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadvehicular',
            name='tipo',
            field=models.CharField(choices=[('CAMIÓN', 'CAMIÓN'), ('CAMIONETA', 'CAMIONETA'), ('TRÁILER', 'TRÁILER'), ('OTRO', 'OTRO')], default='CAMIÓN', max_length=20, verbose_name='Tipo de Vehículo'),
        ),
    ]
