# Generated by Django 5.2.4 on 2025-09-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_alter_unidadvehicular_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_unidad', to='erp.unidadvehicular', verbose_name='Unidad Vehicular Asignada'),
        ),
    ]
