# Generated by Django 5.2.4 on 2025-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_alter_rutas_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA'), ('FINALIZADA CON DIFERIDO', 'FINALIZADA CON DIFERIDO')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
    ]
