# Generated by Django 5.2.4 on 2025-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='is_app',
            field=models.BooleanField(default=True, verbose_name='Creado desde App Móvil'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PROCESANDO', 'PROCESANDO'), ('EN CAMINO', 'EN CAMINO'), ('FINALIZADA', 'FINALIZADA'), ('CANCELADA', 'CANCELADA')], default='ALMACEN VIRTUAL', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
    ]
