# Generated by Django 5.2.4 on 2025-09-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_compra_is_app_alter_compra_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('CANCELADA', 'CANCELADA'), ('FINALIZADA', 'FINALIZADA')], default='SOLICITUD', max_length=30, verbose_name='Estado'),
        ),
    ]
