# Generated by Django 5.2.4 on 2025-09-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='es_producto_nuevo',
            field=models.BooleanField(default=False, verbose_name='Es Nuevo'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='existe_diferencia',
            field=models.BooleanField(default=False, verbose_name='Existe Diferencia'),
        ),
    ]
