# Generated by Django 5.2.4 on 2025-09-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_compradetalle_diferencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='diferencia',
            new_name='cantidad_entrada',
        ),
    ]
