# Generated by Django 5.2.4 on 2025-10-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_rename_diferencia_compradetalle_cantidad_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='falta_inventario',
            field=models.BooleanField(default=False, verbose_name='Falta producto en Inventario'),
        ),
    ]
