# Generated by Django 5.2.4 on 2025-10-05 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_venta_falta_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='alamcen_embarque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_embarque', to='erp.almacen', verbose_name='Almacén de Embarque'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIJO', 'FIJO'), ('VIRT', 'VIRTUAL'), ('RUTA', 'RUTA'), ('COMP', 'COMPRA'), ('HELP', 'HELP CEDIS'), ('EMBA', 'EMBARQUE')], default='FIJO', max_length=4, null=True, verbose_name='Tipo de almacen'),
        ),
    ]
