# Generated by Django 5.2.4 on 2025-10-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_rutas_alamcen_embarque_alter_almacen_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='alamcen_embarque',
            new_name='almacen_embarque',
        ),
    ]
