# Generated by Django 5.2.4 on 2025-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_rename_alamcen_embarque_rutas_almacen_embarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='is_total_cargado',
            field=models.BooleanField(default=False, help_text='Indica si el total de mercancia en la preventa ya fue cargada al almacen de su ruta fue ingresado en su totalidad', verbose_name='Total Cargado'),
        ),
    ]
