# Generated by Django 5.2.4 on 2025-10-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_venta_is_total_cargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFaltanteEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Faltante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_faltantes', to='erp.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_faltantes', to='erp.venta', verbose_name='Venta')),
            ],
        ),
    ]
