# Generated by Django 5.2.4 on 2025-10-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_productofaltanteembarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='is_cargado',
            field=models.BooleanField(default=False, help_text='Indica si este lote ya fue cargado en el almacén de la ruta', verbose_name='Cargado en Almacén'),
        ),
        migrations.DeleteModel(
            name='ProductoFaltanteEmbarque',
        ),
    ]
