# Generated by Django 5.2.4 on 2025-10-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_ventadetalle_is_cargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
