# Generated by Django 5.2.4 on 2025-10-14 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_condicionpago'),
        ('erp', '0044_ordencompradetalle_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='condicion_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.condicionpago', verbose_name='Condición de Pago'),
        ),
    ]
