# Generated by Django 5.2.4 on 2025-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_ordencompra_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='condicion_pago',
            field=models.CharField(blank=True, default='CONTADO', max_length=50, null=True, verbose_name='Condición de Pago'),
        ),
    ]
