# Generated by Django 5.2.4 on 2025-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_alter_ordencompra_condicion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Límite de crédito'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='total_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Total de crédito'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=25, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pagoscompra',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='pagosventa',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio Mayoreo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_publico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio Público'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Monto de Crédito'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='total_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Total de Crédito'),
        ),
        migrations.AlterField(
            model_name='unidadvehicular',
            name='capacidad_carga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de carga en toneladas', max_digits=20, null=True, verbose_name='Capacidad de Carga (Tons)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=25, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ventadetallelote',
            name='cantidad_utilizada',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad Utilizada del Lote'),
        ),
        migrations.AlterField(
            model_name='ventadetallelote',
            name='costo_unitario_lote',
            field=models.DecimalField(decimal_places=2, help_text='Costo del producto en este lote específico', max_digits=20, verbose_name='Costo Unitario del Lote'),
        ),
    ]
