# Generated by Django 5.2.4 on 2025-10-22 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_alter_cliente_limite_credito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('mensaje', 'Mensaje')], default='info', max_length=20)),
                ('url_destino', models.URLField(blank=True, help_text='Enlace opcional al que redirige la notificación.', null=True)),
                ('leida', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida_el', models.DateTimeField(blank=True, null=True)),
                ('leida_por', models.ForeignKey(blank=True, help_text='Usuario que marcó la notificación como leída.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que recibirá la notificación.', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_el'],
            },
        ),
    ]
