# Generated by Django 5.2.4 on 2025-10-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='is_entregado',
            field=models.BooleanField(default=False, help_text='Indica si la venta ya fue entregada al cliente', verbose_name='Entregado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('COMANDERA', 'COMANDERA'), ('MOSTRADOR', 'MOSTRADOR')], default='MOSTRADOR', max_length=20, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='is_entregado',
            field=models.BooleanField(default=False, help_text='Indica si este lote ya fue entregado al cliente', verbose_name='Entregado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error'), ('mensaje', 'mensaje')], default='info', max_length=20),
        ),
    ]
