# Generated by Django 5.2.4 on 2025-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_venta_is_entregado_venta_tipo_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'CONTADO'), ('CRÉDITO', 'CRÉDITO')], default='CONTADO', max_length=50, null=True, verbose_name='Condición de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fase',
            field=models.CharField(choices=[('PRE VENTA', 'PRE VENTA'), ('VENTA COMANDERA', 'VENTA COMANDERA'), ('EN CURSO', 'EN CURSO'), ('TERMINADA', 'TERMINADA'), ('CANCELADA', 'CANCELADA')], default='TERMINADA', max_length=20, verbose_name='Fase'),
        ),
    ]
