# Generated by Django 5.2.4 on 2025-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_venta_condicion_pago_alter_venta_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventa',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
    ]
