# Generated by Django 5.2.4 on 2025-10-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_pagosventa_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosventa',
            name='fecha_pagar',
        ),
    ]
