# Generated by Django 5.2.4 on 2025-10-30 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_condicionpago'),
        ('erp', '0055_alter_cliente_precio_tipo_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['nombre'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.RemoveField(
            model_name='caja',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='caja',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_ruta', to='erp.rutas', verbose_name='Caja de Ruta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_sucursal', to='erp.sucursal', verbose_name='Ubicación (Sucursal)'),
        ),
        migrations.AddField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('RUTA', 'RUTA'), ('SUCURSAL', 'SUCURSAL')], default='SUCURSAL', max_length=20, verbose_name='Tipo de Caja'),
        ),
        migrations.CreateModel(
            name='CajaApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto Inicial')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Monto Final')),
                ('is_abierta', models.BooleanField(default=True, verbose_name='Caja Abierta')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='erp.caja', verbose_name='Caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que abre la caja')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CajaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], default='ENTRADA', max_length=10, verbose_name='Tipo de Transacción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('caja_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='erp.cajaapertura', verbose_name='Apertura de Caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.metodopago', verbose_name='Método de Pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
