# Generated by Django 5.2.4 on 2025-11-03 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_alter_caja_options_remove_caja_ubicacion_caja_ruta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad'),
        ),
        migrations.AddConstraint(
            model_name='cajaapertura',
            constraint=models.UniqueConstraint(condition=models.Q(('is_abierta', True), ('status_model', 'ACTIVE')), fields=('caja',), name='unique_caja_abierta'),
        ),
        migrations.AddConstraint(
            model_name='cajaapertura',
            constraint=models.UniqueConstraint(condition=models.Q(('is_abierta', True), ('status_model', 'ACTIVE')), fields=('usuario',), name='unique_usuario_apertura_abierta'),
        ),
    ]
