# Generated by Django 5.2.4 on 2025-11-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_alter_ventadetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Total Pagado'),
        ),
    ]
