# Generated by Django 5.2.4 on 2025-11-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0058_venta_total_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajatransaccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de la Transacción'),
        ),
    ]
