# Generated by Django 5.2.4 on 2025-11-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_categoriacliente_cliente_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sujeto_credito',
            field=models.BooleanField(default=False, verbose_name='Sujeto a Crédito'),
        ),
    ]
