# Generated by Django 5.2.4 on 2025-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_cliente_sujeto_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ya_terminada',
            field=models.BooleanField(default=False, help_text='Indica si la venta ya fue finalizada', verbose_name='Ya Terminada'),
        ),
    ]
