# Generated by Django 5.2.4 on 2025-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0062_venta_ya_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Cambio Entregado'),
        ),
    ]
