# Generated by Django 5.2.4 on 2025-11-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0063_venta_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajatransaccion',
            name='gasto_tipo',
            field=models.CharField(blank=True, choices=[('GASTO VIATICO XALAPA', 'GASTO VIATICO XALAPA'), ('GASTO VIATICO CORDOBA', 'GASTO VIATICO CORDOBA'), ('GASTO INSUMOS PLASTICOS', 'GASTO INSUMOS PLASTICOS'), ('GASTO MECANICO', 'GASTO MECANICO'), ('OTRO', 'OTRO')], default='', max_length=50, null=True, verbose_name='Tipo de Gasto'),
        ),
        migrations.AlterField(
            model_name='cajatransaccion',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('GASTO', 'GASTO')], default='ENTRADA', max_length=10, verbose_name='Tipo de Transacción'),
        ),
    ]
