# Generated by Django 5.2.4 on 2025-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_cajatransaccion_gasto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ignorada',
            field=models.BooleanField(default=False, help_text='Indica si la venta fue ignorada en el sistema para cierre', verbose_name='Venta Ignorada'),
        ),
    ]
