# Generated by Django 5.2.4 on 2025-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0065_venta_ignorada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Cantidad'),
        ),
    ]
