# Generated by Django 5.2.4 on 2025-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0066_alter_compradetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=25, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='precio',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=25, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pagoscompra',
            name='monto',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Monto'),
        ),
    ]
