# Generated by Django 5.2.4 on 2025-11-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0067_alter_compradetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIJO', 'FIJO'), ('VIRT', 'VIRTUAL'), ('RUTA', 'RUTA'), ('COMP', 'COMPRA'), ('HELP', 'HELP CEDIS'), ('EMBA', 'EMBARQUE'), ('TRAS', 'TRASPASO')], default='FIJO', max_length=4, null=True, verbose_name='Tipo de almacen'),
        ),
    ]
