# Generated by Django 5.2.4 on 2025-11-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0068_alter_almacen_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='is_ruta_fijo',
            field=models.BooleanField(default=False, verbose_name='Es Ruta Fijo'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='almacen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='erp.almacen', verbose_name='Almacén para vender (tara abierta)'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='almacen_embarque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_embarque', to='erp.almacen', verbose_name='Almacén de pedidos'),
        ),
    ]
