# Generated by Django 5.2.4 on 2025-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0069_almacen_is_ruta_fijo_alter_rutas_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=5, max_digits=20, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=25, verbose_name='Subtotal'),
        ),
    ]
