# Generated by Django 5.2.4 on 2025-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0070_alter_ventadetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=25, verbose_name='Cambio Entregado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_pagado',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=25, verbose_name='Total Pagado'),
        ),
    ]
