# Generated by Django 5.2.4 on 2025-11-24 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0071_alter_venta_cambio_alter_venta_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscompra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_compra', to='erp.ordencompra', verbose_name='Orden de Compra'),
        ),
    ]
