# Generated by Django 5.2.4 on 2025-11-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0072_pagoscompra_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscompra',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pagoscompra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_orden_compra', to='erp.ordencompra', verbose_name='Orden de Compra'),
        ),
    ]
