# Generated by Django 5.2.4 on 2025-11-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0073_pagoscompra_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscompra',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='erp.compra', verbose_name='Compra'),
        ),
    ]
