# Generated by Django 5.2.4 on 2025-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0074_alter_pagoscompra_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='condicion_pago',
            field=models.CharField(blank=True, default='CONTADO', max_length=50, null=True, verbose_name='Condición de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'CONTADO'), ('CRÉDITO', 'CRÉDITO'), ('MIXTA', 'MIXTA')], default='CONTADO', max_length=50, null=True, verbose_name='Condición de Pago'),
        ),
    ]
