# Generated by Django 5.2.4 on 2025-11-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_compra_condicion_pago_alter_venta_condicion_pago'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cajaapertura',
            name='unique_caja_abierta',
        ),
    ]
