# Generated by Django 5.2.4 on 2025-12-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0076_remove_cajaapertura_unique_caja_abierta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='pertence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_pertence', to='erp.almacen', verbose_name='Pertenece a o (obtener almacen tara)'),
        ),
    ]
