# Generated by Django 5.2.4 on 2025-12-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0078_alter_almacen_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20, verbose_name='Cantidad Entregada'),
        ),
        migrations.CreateModel(
            name='Insidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Insidencia')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución Aplicada')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Insidencia Resuelta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insidencia',
                'verbose_name_plural': 'Insidencias',
            },
        ),
    ]
