# Generated by Django 5.2.4 on 2025-12-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0079_ventadetalle_cantidad_entregada_insidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_compra',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Foranea', 'Foranea')], default='Local', max_length=20, null=True, verbose_name='Tipo de Compra'),
        ),
    ]
