# Generated by Django 5.2.4 on 2025-12-12 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0080_producto_tipo_compra'),
        ('inventario', '0031_loteproductoembarque_is_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsidenciaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cantidad Afectada')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Atención')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('insidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_insidencia', to='erp.insidencia', verbose_name='Insidencia')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insidencias_lote', to='inventario.loteinventario', verbose_name='Lote de Inventario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote en Insidencia',
                'verbose_name_plural': 'Lotes en Insidencias',
            },
        ),
    ]
