# Generated by Django 5.2.4 on 2025-12-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0082_gastoscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='cantidad_cargada',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20, verbose_name='Cantidad Cargada'),
        ),
    ]
