# Generated by Django 5.2.4 on 2025-12-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0083_ventadetalle_cantidad_cargada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='cantidad_logistica',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20, verbose_name='Cantidad Logística'),
        ),
    ]
