# Generated by Django 5.2.9 on 2026-01-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0084_ventadetalle_cantidad_logistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CRÉDITO', 'CRÉDITO'), ('MIXTA', 'MIXTA')], default='CONTADO', max_length=50, verbose_name='Condición de Pago'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CRÉDITO', 'CRÉDITO'), ('MIXTA', 'MIXTA')], default='CONTADO', max_length=50, verbose_name='Condición de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CRÉDITO', 'CRÉDITO'), ('MIXTA', 'MIXTA')], default='CONTADO', max_length=50, verbose_name='Condición de Pago'),
        ),
    ]
