# Generated by Django 5.2.9 on 2026-02-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0085_alter_compra_condicion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
