# Generated by Django 5.2.9 on 2026-02-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0086_compra_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad_entrada',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25, verbose_name='Diferencia'),
        ),
    ]
