# Generated by Django 5.2.9 on 2026-02-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0087_alter_compradetalle_cantidad_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidencialote',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Cantidad Afectada'),
        ),
    ]
