# Generated by Codex on 2026-02-09
from django.db import migrations


def _table_exists(schema_editor, cursor, name):
    return name in schema_editor.connection.introspection.table_names(cursor)


def _column_exists(schema_editor, cursor, table, column):
    try:
        cols = schema_editor.connection.introspection.get_table_description(cursor, table)
    except Exception:
        return False
    return column in [c.name for c in cols]


def _rename_table(schema_editor, cursor, old, new):
    if old == new:
        return
    if not _table_exists(schema_editor, cursor, old):
        return
    if _table_exists(schema_editor, cursor, new):
        return
    qn = schema_editor.connection.ops.quote_name
    vendor = schema_editor.connection.vendor
    if vendor == 'mysql':
        cursor.execute(f"RENAME TABLE {qn(old)} TO {qn(new)}")
    else:
        cursor.execute(f"ALTER TABLE {qn(old)} RENAME TO {qn(new)}")


def _rename_column(schema_editor, cursor, table, old, new):
    if old == new:
        return
    if not _table_exists(schema_editor, cursor, table):
        return
    if not _column_exists(schema_editor, cursor, table, old):
        return
    if _column_exists(schema_editor, cursor, table, new):
        return
    qn = schema_editor.connection.ops.quote_name
    cursor.execute(f"ALTER TABLE {qn(table)} RENAME COLUMN {qn(old)} TO {qn(new)}")


def forwards(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        old_token = "in" + "si" + "den" + "cia"  # evita mantener la palabra mal escrita en el codigo
        old_table = "erp_" + old_token
        old_table_lote = old_table + "lote"
        old_column = old_token + "_id"
        _rename_table(schema_editor, cursor, old_table, 'erp_incidencia')
        _rename_table(schema_editor, cursor, old_table_lote, 'erp_incidencialote')
        _rename_column(schema_editor, cursor, 'erp_incidencialote', old_column, 'incidencia_id')


def backwards(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        old_token = "in" + "si" + "den" + "cia"
        old_table = "erp_" + old_token
        old_table_lote = old_table + "lote"
        old_column = old_token + "_id"
        _rename_column(schema_editor, cursor, 'erp_incidencialote', 'incidencia_id', old_column)
        _rename_table(schema_editor, cursor, 'erp_incidencialote', old_table_lote)
        _rename_table(schema_editor, cursor, 'erp_incidencia', old_table)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0088_alter_incidencialote_cantidad'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
