# Generated by Django 5.2.4 on 2025-08-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_sucursal_empresa'),
        ('inventario', '0003_alter_loteinventario_fecha_ingreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, help_text='Almacén de destino para el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='erp.almacen'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén donde se realiza el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.almacen'),
        ),
        migrations.CreateModel(
            name='ProductosMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.loteinventario')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.movimientoinventario')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto en Movimiento',
                'verbose_name_plural': 'Productos en Movimientos',
            },
        ),
    ]
