# Generated by Django 5.2.4 on 2025-08-20 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_movimientoinventario_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='fase',
            field=models.CharField(choices=[('FASE_PROCESO', 'En Proceso'), ('FASE_TERMINADA', 'Terminada')], default='FASE_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='productosmovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productosMovimiento', to='inventario.movimientoinventario'),
        ),
    ]
