# Generated by Django 5.2.4 on 2025-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientoinventario_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='alert_cantidad',
            field=models.BooleanField(default=False, help_text='Indica si la cantidad es menor a la que salió del traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo_alerta',
            field=models.CharField(blank=True, choices=[('MAS', 'Mayor a lo esperado'), ('MENOS', 'Menor a lo esperado')], help_text='Tipo de alerta para el movimiento', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA_ABASTECIMIENTO', 'Abastecimiento'), ('ENTRADA_TRASPASO', 'Traspaso'), ('SALIDA_VENTA', 'Venta'), ('SALIDA_TRASPASO', 'Traspaso'), ('SALIDA_MERMA', 'Merma'), ('SALIDA_TRANSFORMACION', 'Transformación salidas'), ('AJUSTE_MANUAL', 'Ajuste manual')], max_length=30),
        ),
    ]
