# Generated by Django 5.2.4 on 2025-08-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientoinventario_alert_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fase',
            field=models.CharField(choices=[('FASE PROCESO', 'En Proceso'), ('FASE TERMINADA', 'Terminada')], default='FASE PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA ABASTECIMIENTO', 'Abastecimiento'), ('ENTRADA TRASPASO', 'Traspaso'), ('SALIDA VENTA', 'Venta'), ('SALIDA TRASPASO', 'Traspaso'), ('SALIDA MERMA', 'Merma'), ('SALIDA TRANSFORMACION', 'Transformación salidas'), ('AJUSTE MANUAL', 'Ajuste manual')], max_length=30),
        ),
    ]
