# Generated by Django 5.2.4 on 2025-08-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_movimientoinventario_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteinventario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Solo para almacenes CEDIS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.rack'),
        ),
        migrations.DeleteModel(
            name='UbicacionRack',
        ),
    ]
