# Generated by Django 5.2.4 on 2025-08-26 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_remove_sucursal_almacen_sucursal_almacenes_and_more'),
        ('inventario', '0008_alter_loteinventario_ubicacion_delete_ubicacionrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['almacen', 'status_model', 'cantidad'], name='inventario__almacen_c26bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['producto', 'almacen', 'status_model'], name='inventario__product_8c8aba_idx'),
        ),
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['status_model', 'cantidad'], name='inventario__status__d16e33_idx'),
        ),
    ]
