# Generated by Django 5.2.4 on 2025-08-27 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_producto_horas_caducidad'),
        ('inventario', '0009_loteinventario_inventario__almacen_c26bf9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['ubicacion', 'status_model', 'cantidad'], name='inventario__ubicaci_55fa1e_idx'),
        ),
        migrations.AddIndex(
            model_name='loteinventario',
            index=models.Index(fields=['producto', 'ubicacion', 'status_model'], name='inventario__product_21b0cb_idx'),
        ),
    ]
