# Generated by Django 5.2.4 on 2025-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_loteinventario_inventario__ubicaci_55fa1e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fase',
            field=models.CharField(choices=[('FASE PROCESO', 'FASE PROCESO'), ('FASE TERMINADA', 'FASE TERMINADA')], default='FASE PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA ABASTECIMIENTO', 'ENTRADA ABASTECIMIENTO'), ('ENTRADA TRASPASO', 'ENTRADA TRASPASO'), ('SALIDA VENTA', 'SALIDA VENTA'), ('SALIDA TRASPASO', 'SALIDA TRASPASO'), ('SALIDA MERMA', 'SALIDA MERMA'), ('SALIDA TRANSFORMACION', 'SALIDA TRANSFORMACION'), ('AJUSTE MANUAL', 'AJUSTE MANUAL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'SALIDA'), ('ENTRADA', 'ENTRADA'), ('AJUSTE', 'AJUSTE')], default='ENTRADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_alerta',
            field=models.CharField(blank=True, choices=[('MAS', 'MAS'), ('MENOS', 'MENOS')], help_text='Tipo de alerta para el movimiento', max_length=10, null=True),
        ),
    ]
