# Generated by Django 5.2.4 on 2025-09-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_compra_is_app_alter_compra_estado_and_more'),
        ('inventario', '0011_alter_movimientoinventario_fase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fase', models.CharField(choices=[('SOLICITUD', 'SOLICITUD'), ('ATENDIDO', 'ATENDIDO'), ('CANCELADO', 'CANCELADO')], default='SOLICITUD', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_producto', to='erp.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto en Solicitud',
                'verbose_name_plural': 'Productos en Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
    ]
