# Generated by Django 5.2.4 on 2025-10-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_productossolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA ABASTECIMIENTO', 'ENTRADA ABASTECIMIENTO'), ('ENTRADA TRASPASO', 'ENTRADA TRASPASO'), ('ENTRADA TRASPASO VIRTUAL', 'ENTRADA TRASPASO VIRTUAL'), ('SALIDA VENTA', 'SALIDA VENTA'), ('SALIDA TRASPASO', 'SALIDA TRASPASO'), ('SALIDA MERMA', 'SALIDA MERMA'), ('SALIDA TRANSFORMACION', 'SALIDA TRANSFORMACION'), ('SALIDA TRASPASO VIRTUAL', 'SALIDA TRASPASO VIRTUAL'), ('AJUSTE MANUAL', 'AJUSTE MANUAL')], max_length=30),
        ),
    ]
