# Generated by Django 5.2.4 on 2025-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_productoembarque_loteembarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA ABASTECIMIENTO', 'ENTRADA ABASTECIMIENTO'), ('ENTRADA TRASPASO', 'ENTRADA TRASPASO'), ('ENTRADA TRASPASO VIRTUAL', 'ENTRADA TRASPASO VIRTUAL'), ('ENTRADA EMBARQUE', 'ENTRADA EMBARQUE'), ('SALIDA VENTA', 'SALIDA VENTA'), ('SALIDA TRASPASO', 'SALIDA TRASPASO'), ('SALIDA MERMA', 'SALIDA MERMA'), ('SALIDA TRANSFORMACION', 'SALIDA TRANSFORMACION'), ('SALIDA TRASPASO VIRTUAL', 'SALIDA TRASPASO VIRTUAL'), ('SALIDA EMBARQUE', 'SALIDA EMBARQUE'), ('AJUSTE MANUAL', 'AJUSTE MANUAL')], max_length=30),
        ),
    ]
