# Generated by Django 5.2.4 on 2025-10-07 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_ventadetalle_is_cargado_and_more'),
        ('inventario', '0015_alter_movimientoinventario_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoembarque',
            name='ruta',
        ),
        migrations.CreateModel(
            name='EmbarqueReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('fase', models.CharField(choices=[('CARGA', 'CARGA'), ('REPARTO', 'REPARTO'), ('TERMINADO', 'TERMINADO'), ('CANCELADO', 'CANCELADO')], default='CARGA', max_length=20)),
                ('fecha_embarque', models.DateTimeField(auto_now_add=True)),
                ('total_preventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_productos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='erp.rutas')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productoembarque',
            name='embarque',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.embarquereparto'),
        ),
        migrations.DeleteModel(
            name='LoteEmbarque',
        ),
    ]
