# Generated by Django 5.2.4 on 2025-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_productoembarque_ruta_embarquereparto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoembarque',
            name='cantidad_vendida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad vendida del producto', max_digits=10),
        ),
        migrations.AddField(
            model_name='productoembarque',
            name='is_vendido',
            field=models.BooleanField(default=False, help_text='Indica si el producto es  vendido'),
        ),
    ]
