# Generated by Django 5.2.4 on 2025-10-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_productoembarque_cantidad_vendida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarquereparto',
            name='total_productos',
        ),
    ]
