# Generated by Django 5.2.4 on 2025-10-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_ventadetalle_is_cargado_and_more'),
        ('inventario', '0018_remove_embarquereparto_total_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarquereparto',
            name='total_preventas',
        ),
        migrations.AddField(
            model_name='productoembarque',
            name='preventa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_embarque_venta', to='erp.venta'),
        ),
    ]
