# Generated by Django 5.2.4 on 2025-10-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_alter_ordencompra_condicion_pago'),
        ('inventario', '0019_remove_embarquereparto_total_preventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productossolicitud',
            name='almacen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_almacen', to='erp.almacen'),
        ),
        migrations.AddField(
            model_name='productossolicitud',
            name='motivo',
            field=models.CharField(choices=[('BAJA EXISTENCIA', 'BAJA EXISTENCIA'), ('PREVENTA INCOMPLETA', 'PREVENTA INCOMPLETA')], default='BAJA EXISTENCIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='productossolicitud',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_producto', to='erp.producto'),
        ),
    ]
