# Generated by Django 5.2.4 on 2025-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_productossolicitud_almacen_productossolicitud_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='loteinventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productoembarque',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productoembarque',
            name='cantidad_vendida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad vendida del producto', max_digits=20),
        ),
        migrations.AlterField(
            model_name='productosmovimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productosmovimiento',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productosmovimiento',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productossolicitud',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='cantidad_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='costo_total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='costo_unitario_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformaciondetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformaciondetalle',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transformaciondetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
