# Generated by Django 5.2.4 on 2025-11-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_solicitudtraspaso_solicitudtraspasodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='detalle_nota',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
