# Generated by Django 5.2.4 on 2025-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_movimientoinventario_detalle_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
