# Generated by Django 5.2.4 on 2025-12-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_loteinventario_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformacion',
            name='cantidad_final',
        ),
        migrations.RemoveField(
            model_name='transformacion',
            name='costo_total_final',
        ),
        migrations.RemoveField(
            model_name='transformacion',
            name='costo_unitario_final',
        ),
        migrations.RemoveField(
            model_name='transformacion',
            name='producto_final',
        ),
        migrations.AddField(
            model_name='transformacion',
            name='movimiento_entrada',
            field=models.ForeignKey(blank=True, help_text='Movimiento de entrada asociado a la transformación productos resultantes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformaciones_entrada', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='transformacion',
            name='movimiento_salida',
            field=models.ForeignKey(blank=True, help_text='Movimiento de salida asociado a la transformación o merma productos a transformar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformaciones_salida', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='transformacion',
            name='tipo',
            field=models.CharField(choices=[('MERMA', 'MERMA'), ('TRANSFORMACION', 'TRANSFORMACION')], default='TRANSFORMACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA ABASTECIMIENTO', 'ENTRADA ABASTECIMIENTO'), ('ENTRADA TRASPASO', 'ENTRADA TRASPASO'), ('ENTRADA TRASPASO VIRTUAL', 'ENTRADA TRASPASO VIRTUAL'), ('ENTRADA EMBARQUE', 'ENTRADA EMBARQUE'), ('ENTRADA VENTA CANCELADA', 'ENTRADA VENTA CANCELADA'), ('ENTRADA TRANSFORMACION', 'ENTRADA TRANSFORMACION'), ('SALIDA VENTA', 'SALIDA VENTA'), ('SALIDA TRASPASO', 'SALIDA TRASPASO'), ('SALIDA MERMA', 'SALIDA MERMA'), ('SALIDA TRANSFORMACION', 'SALIDA TRANSFORMACION'), ('SALIDA TRASPASO VIRTUAL', 'SALIDA TRASPASO VIRTUAL'), ('SALIDA EMBARQUE', 'SALIDA EMBARQUE'), ('AJUSTE MANUAL', 'AJUSTE MANUAL')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TransformacionDetalle',
        ),
    ]
