# Generated by Django 5.2.4 on 2025-12-05 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0076_remove_cajaapertura_unique_caja_abierta'),
        ('inventario', '0026_remove_transformacion_cantidad_final_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarquereparto',
            name='fecha_embarque',
        ),
        migrations.RemoveField(
            model_name='productoembarque',
            name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='productoembarque',
            name='is_tara_abierta',
        ),
        migrations.RemoveField(
            model_name='productoembarque',
            name='is_vendido',
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_pedidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_tara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto_tara', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='ventas',
            field=models.ManyToManyField(related_name='embarques_ruta', to='erp.venta'),
        ),
        migrations.CreateModel(
            name='LoteProductoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_embarque', to='inventario.loteinventario')),
                ('producto_embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.productoembarque')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
