# Generated by Django 5.2.4 on 2025-12-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_remove_embarquereparto_fecha_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteinventario',
            name='lote_herencia',
            field=models.ForeignKey(blank=True, help_text='Lote del cual se deriva este lote (en caso de transformaciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.loteinventario'),
        ),
    ]
