# Generated by Django 5.2.4 on 2025-12-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_loteinventario_lote_herencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarquereparto',
            name='movimiento_inventario_pedidos',
        ),
        migrations.RemoveField(
            model_name='embarquereparto',
            name='movimiento_inventario_tara',
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_pedidos_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto_entrada', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_pedidos_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto_salida', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_tara_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto_tara_entrada', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='movimiento_inventario_tara_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_reparto_tara_salida', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='productoembarque',
            name='tipo',
            field=models.CharField(choices=[('TARA', 'TARA'), ('PEDIDO', 'PEDIDO')], default='TARA', max_length=20),
        ),
    ]
