# Generated by Django 5.2.4 on 2025-12-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_remove_embarquereparto_movimiento_inventario_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarquereparto',
            name='fecha_finalizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embarquereparto',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
