# Generated by Django 5.2.4 on 2025-12-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_embarquereparto_fecha_finalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproductoembarque',
            name='is_interno',
            field=models.BooleanField(default=False),
        ),
    ]
