# Generated by Django 5.2.4 on 2025-12-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_loteproductoembarque_is_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoembarque',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='productoembarque',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
