# Generated by Django 5.2.4 on 2025-12-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0083_ventadetalle_cantidad_cargada'),
        ('inventario', '0032_productoembarque_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarquereparto',
            name='apertura_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_embarque_reparto', to='erp.cajaapertura'),
        ),
    ]
