# Generated by Django 5.2.4 on 2025-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_embarquereparto_apertura_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoembarque',
            name='is_cargado',
            field=models.BooleanField(default=False),
        ),
    ]
