# Generated by Django 5.2.4 on 2025-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_productoembarque_is_cargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoembarque',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
