# Generated by Django 5.2.9 on 2026-02-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_productoembarque_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='loteproductoembarque',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productoembarque',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productoembarque',
            name='cantidad_entregada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productoembarque',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productosmovimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productossolicitud',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
