# Generated by Django 5.2.4 on 2025-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditocliente',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
