# Generated by Django 5.2.4 on 2025-11-11 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_alter_creditocliente_monto'),
        ('erp', '0062_venta_ya_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditocliente',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos', to='erp.venta'),
        ),
    ]
