# Generated by Django 5.2.9 on 2026-02-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_creditoproveedor_pagoscreditoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscreditoproveedor',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
