# Generated by Django 5.2.9 on 2026-02-16 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_add_referencia_pagos_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionPrelacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_model', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], db_index=True, max_length=20)),
                ('entidad_id', models.PositiveIntegerField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación de prelación de pago',
                'verbose_name_plural': 'Operaciones de prelación de pago',
                'constraints': [models.UniqueConstraint(fields=('tipo', 'entidad_id', 'idempotency_key'), name='credito_unique_prelacion_idempotency')],
            },
        ),
    ]
