# Generated by Django 5.2.4 on 2025-07-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('id',)},
        ),
        migrations.AddIndex(
            model_name='codigopostal',
            index=models.Index(fields=['codigo_postal', 'id'], name='direccion_c_codigo__10bd59_idx'),
        ),
        migrations.AddIndex(
            model_name='colonia',
            index=models.Index(fields=['id'], name='direccion_c_id_fdf349_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['id'], name='direccion_m_id_bf2fba_idx'),
        ),
    ]
