# Generated by Django 5.2.4 on 2025-07-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_user', 'VER USUARIO'), ('can_update_user', 'ACTUALIZAR USUARIO'), ('can_create_user', 'CREAR USUARIO'), ('can_delete_user', 'ELIMINAR USUARIO')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
