# Generated by Django 5.2.4 on 2025-08-01 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0002_alter_municipio_unique_together_and_more'),
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_postal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.codigopostal')),
                ('colonia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.colonia')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.municipio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
