# Generated by Django 5.2.4 on 2025-10-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_alter_cliente_precio_tipo_caja'),
        ('usuarios', '0003_alter_usuario_telefono_1_direccionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.almacen', verbose_name='Almacén asignado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal asignada al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.sucursal', verbose_name='Sucursal asignada'),
        ),
    ]
